("metabase.driver.sql-jdbc.connection/connection-details->spec ([driver details-map])"
 "metabase.driver.sql-jdbc.execute/set-timezone-sql ([driver])"
 "metabase.driver.sql-jdbc.sync/active-tables ([driver metadata])"
 "metabase.driver.sql-jdbc.sync/column->base-type ([driver column-type])"
 "metabase.driver.sql-jdbc.sync/column->special-type ([driver native-type column-name])"
 "metabase.driver.sql-jdbc.sync/database-type->base-type ([driver column-type])"
 "metabase.driver.sql-jdbc.sync/enum-types ([driver database])"
 "metabase.driver.sql-jdbc.sync/excluded-schemas ([driver])"
 "metabase.driver.sql.query-processor/->honeysql ([driver x])"
 "metabase.driver.sql.query-processor/apply-top-level-clause ([driver top-level-clause honeysql-form query])"
 "metabase.driver.sql.query-processor/current-datetime-fn ([driver])"
 "metabase.driver.sql.query-processor/date ([driver unit field-or-value])"
 "metabase.driver.sql.query-processor/field->alias ([driver field])"
 "metabase.driver.sql.query-processor/field->identifier ([driver field])"
 "metabase.driver.sql.query-processor/quote-style ([driver])"
 "metabase.driver.sql.query-processor/string-length-fn ([this field-key])"
 "metabase.driver.sql.query-processor/unix-timestamp->timestamp ([driver seconds-or-milliseconds field-or-value])"
 "metabase.driver.sql/->prepared-substitution ([driver x])"
 "metabase.driver/available? ([driver])"
 "metabase.driver/can-connect? ([driver details])"
 "metabase.driver/current-db-time ([driver database])"
 "metabase.driver/date-interval ([driver unit amount])"
 "metabase.driver/describe-database ([driver database])"
 "metabase.driver/describe-table ([driver database table])"
 "metabase.driver/describe-table-fks ([this database table])"
 "metabase.driver/details-fields ([driver])"
 "metabase.driver/display-name ([driver])"
 "metabase.driver/execute-query ([driver query])"
 "metabase.driver/format-custom-field-name ([driver custom-field-name])"
 "metabase.driver/humanize-connection-error-message ([this message])"
 "metabase.driver/mbql->native ([driver query])"
 "metabase.driver/notify-database-updated ([driver database])"
 "metabase.driver/process-query-in-context ([driver qp])"
 "metabase.driver/supports? ([driver feature])"
 "metabase.driver/sync-in-context ([driver database f])"
 "metabase.driver/table-rows-seq ([driver database table])"
 "metabase.test.data.interface/aggregate-column-info ([driver aggregation-type] [driver aggregation-type field])"
 "metabase.test.data.interface/create-db! ([driver database-definition & {:keys [skip-drop-db?]}])"
 "metabase.test.data.interface/database->connection-details ([[driver context database-definition]])"
 "metabase.test.data.interface/expected-base-type->actual ([driver base-type])"
 "metabase.test.data.interface/format-name ([driver table-or-field-name])"
 "metabase.test.data.interface/has-questionable-timezone-support? ([driver])"
 "metabase.test.data.interface/id-field-type ([driver])"
 "metabase.test.data.sql-jdbc.execute/execute-sql! ([driver context dbdef sql] :style/indent 2)"
 "metabase.test.data.sql-jdbc.load-data/load-data! ([driver dbdef tabledef])"
 "metabase.test.data.sql-jdbc.spec/database->spec ([driver context dbdef])"
 "metabase.test.data.sql.ddl/create-db-ddl-statements ([driver dbdef & {:as options}])"
 "metabase.test.data.sql.ddl/drop-db-ddl-statements ([driver dbdef & {:keys [skip-drop-db?]}])"
 "metabase.test.data.sql/add-fk-sql ([driver dbdef tabledef fielddef])"
 "metabase.test.data.sql/create-db-sql ([driver dbdef])"
 "metabase.test.data.sql/create-table-sql ([driver dbdef tabledef])"
 "metabase.test.data.sql/drop-db-if-exists-sql ([driver dbdef])"
 "metabase.test.data.sql/drop-table-if-exists-sql ([driver dbdef tabledef])"
 "metabase.test.data.sql/field-base-type->sql-type ([driver base-type])"
 "metabase.test.data.sql/inline-column-comment-sql ([driver comment])"
 "metabase.test.data.sql/inline-table-comment-sql ([driver comment])"
 "metabase.test.data.sql/pk-field-name ([driver])"
 "metabase.test.data.sql/pk-sql-type ([driver])"
 "metabase.test.data.sql/prepare-identifier ([driver s])"
 "metabase.test.data.sql/qualified-name-components ([driver database-name? table-name? field-name?])"
 "metabase.test.data.sql/qualify+quote-name ([driver database-name? table-name? field-name?])"
 "metabase.test.data.sql/quote-name ([driver s])"
 "metabase.test.data.sql/standalone-column-comment-sql ([driver dbdef tabledef fielddef])"
 "metabase.test.data.sql/standalone-table-comment-sql ([driver dbdef tabledef])")
